export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

export const CART_UPDATE_PAYMENT_METHOD_REQUEST =
  "CART_UPDATE_PAYMENT_METHOD_REQUEST";
export const CART_UPDATE_PAYMENT_METHOD_SUCCESS =
  "CART_UPDATE_PAYMENT_METHOD_SUCCESS";
export const CART_UPDATE_PAYMENT_METHOD_FAIL =
  "CART_UPDATE_PAYMENT_METHOD_FAIL";
export const CART_UPDATE_PAYMENT_METHOD_RESET =
  "CART_UPDATE_PAYMENT_METHOD_RESET";
